### ISSUE TITLE
Does not randomize first item

### ISSUE THREAD

**Issue by sln45** [ramzan/Delist#1]
Delist never randomizes an initial list; it will always present the first item you add, and only randomize the list afterwards.

**Comment by ramzan** [comment]
Are you submitting one task at a time? If so, you are presented the first item because it is the only item in the collection at the time, making it random.
If you submit multiple tasks to an empty collection, the first item will be randomized. Here's an example:

![output](https://user-images.githubusercontent.com/55637406/132129761-17631b9f-0648-4c26-aa09-24dbc78d0856.gif)

**Comment by sln45** [comment]
Oh! I didn't even realize that was an option. Thank you for clarifying.
